### ISSUE TITLE
Can't install Package with Smyfony "3.3.*"

### ISSUE THREAD

**Issue by primus852** [caxy/HtmlDiffBundle#16]
I have an issue installing the package, I get these errors:

` Problem 1
    - Installation request for caxy/htmldiff-bundle ^0.1.1 -> satisfiable by caxy/htmldiff-bundle[v0.1.1].
    - caxy/htmldiff-bundle v0.1.1 requires symfony/framework-bundle ~2.1 -> satisfiable by symfony/framework-bundle[2.1.x-dev,.., v2.8.9] but these conflict with your requirements or minimum-stability.`

This is my composer:

        "php": ">=5.5.9"
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "friendsofsymfony/user-bundle": "~2.0",
        "h4cc/wkhtmltoimage-amd64": "^0.12.3",
        "h4cc/wkhtmltopdf-amd64": "^0.12.3",
        "incenteev/composer-parameter-handler": "^2.0",
        "knplabs/knp-snappy-bundle": "^1.4",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^3.0.2",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/symfony": "3.3.*",
        "twig/twig": "^1.0||^2.0",
        "oro/doctrine-extensions": "^1.2",
        "php-imap/php-imap": "^2.0",
        "defuse/php-encryption": "^2.1",
        "sentry/sentry-symfony": "^0.8.4",
        "wemersonjanuario/wkhtmltopdf-windows": "0.12.2.3",
        "symfony/framework-bundle": "^3.3"

I also did `composer clear-cache` but to no avail. Any ideas?

**Comment by jschroed91** [comment]
Hi @primus852 - this is most likely because the latest tag doesn't include the pull request to support Symfony 3+ (https://github.com/caxy/HtmlDiffBundle/pull/14)

I will tag a new release and then you can retry.

**Comment by jschroed91** [comment]
@primus852 Tagged a new release https://github.com/caxy/HtmlDiffBundle/releases/tag/v0.1.2 that includes the update to the composer.json file to allow installation w/ Symfony 3+. Give it a try now and let me know if that works for you so I can close this.

**Comment by primus852** [comment]
Works, thank you!
